name: MinetorioEnhanced
version: '1.0.0'
main: me.darksoul.minetorioEnhanced.MinetorioEnhanced
api-version: '1.21'

dependencies:
  server:
    Minetorio:
      load: BEFORE
      required: true
    AbyssalLib:
      load: BEFORE
      required: true
